---
- hosts: all
  vars:
    apt_packages:
      - libmysqlclient-dev
      - mysql-client
      - mysql-server
      - python-pip
      - build-essential
      - python-dev
      - python-virtualenv
      - libncurses5-dev
      - python-mysqldb
      - openjdk-6-jre
      - npm
      - nodejs-legacy
      - git
      - emacs24-nox
      - postfix
      - libjpeg-dev
      - libxml2-dev
      - libxslt1-dev
      - python-dev
    pip_packages:
      - virtualenvwrapper
    venv_name: starcellbio
    venv_path: ~/.virtualenvs/{{ venv_name }}
    db_name: starcellbio
    db_user: starcellbio
    db_pass: 136a411ed9e8592089444b7164ffaf84
  tasks:
    - name: Install debian packages
      sudo: yes
      apt: name={{ item }} update_cache=yes
      with_items: "{{ apt_packages }}"

    - name: Install pip packages
      sudo: yes
      pip: name={{ item }}
      with_items: "{{ pip_packages }}"

    - name: Create venv
      shell: >
        executable=/bin/bash
        creates={{ venv_path }}
        . /usr/local/bin/virtualenvwrapper.sh &&
        mkvirtualenv {{ venv_name }}

    - name: Install requirements
      pip: requirements='/vagrant/requirements.txt' virtualenv={{ venv_path }}

    - name: Install dev requirements
      pip: requirements='/vagrant/requirements.dev.txt' virtualenv={{ venv_path }}

    - name: Install node packages
      npm: path=/vagrant/html_app

    - name: Install jqDialog
      get_url:
        url: https://raw.githubusercontent.com/knadh/jqdialog/master/jqdialog.js
        dest: /vagrant/html_app/js/

    - name: Create database
      sudo: yes
      mysql_db: name={{ db_name }}

    - name: Create user
      sudo: yes
      mysql_user: >
        name={{ db_user }}
        password={{ db_pass }}
        priv={{ db_name }}.*:ALL

    - name: Sync DB
      shell: >
        executable=/bin/bash
        chdir=/vagrant
        {{ venv_path }}/bin/python manage.py migrate --noinput

    - name: Load data
      shell: >
        executable=/bin/bash
        chdir=/vagrant
        {{ venv_path }}/bin/python manage.py loaddata backend auth

    - name: Collect Static
      shell: >
        executable=/bin/bash
        chdir=/vagrant
        {{ venv_path }}/bin/python manage.py collectstatic --noinput

    - name: Compile files
      shell: >
        executable=/bin/bash
        chdir=/vagrant/html_app
        {{ venv_path }}/bin/python build.py
      environment:
        PROJECT_HOME: "/vagrant"
        PATH: "/vagrant/node_modules/.bin:{{ ansible_env.PATH }}"


    - name: Drop profile
      shell: >
        creates=~/.ansible-profile
        cat /vagrant/provision/vagrant_env >> ~/.profile;
        touch ~/.ansible-profile
